databases:
  - name: occassia-db
    plan: free

services:
  - type: web
    name: occassia-api
    runtime: docker
    rootDir: backend
    plan: free
    healthCheckPath: /api/v1/docs
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: occassia-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: occassia-db
          property: password
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ALLOWED_ORIGINS
        sync: false
