import { Link, useParams } from 'react-router-dom';
import { ArrowLeft, CheckCircle2, UserRound } from 'lucide-react';
import { useEffect, useState } from 'react';
import { cardsApi, guestsApi } from '../api';
import type { Guest } from '../types';
import EventTabs from '../components/EventTabs';
import NfcCapture from '../components/NfcCapture';
import { useUiStore } from '../store/uiStore';

export default function CardAssignmentPage() {
  const { id } = useParams<{ id: string }>(); const [guests, setGuests] = useState<Guest[]>([]); const [guestId, setGuestId] = useState(''); const [uid, setUid] = useState(''); const [saving, setSaving] = useState(false); const showToast = useUiStore((s) => s.showToast);
  useEffect(() => { if (!id) return; guestsApi.assignable(id).then((r) => setGuests(r.data)).catch((err: any) => { console.error('[Cards] Assignable guests load failed', err); showToast(err.response?.data?.message || 'Eligible guests could not be loaded. Refresh and try again.', 'error'); }); }, [id, showToast]);
  const selected = guests.find((guest) => guest.id === guestId);
  const assign = async () => { if (!selected) { showToast('Select a confirmed and paid guest first.', 'error'); return; } if (!uid.trim()) { showToast('Capture an NFC card before assigning it.', 'error'); return; } setSaving(true); try { await cardsApi.assign(selected.id, uid.trim()); showToast(`Card assigned to ${selected.fullName}.`, 'success'); setGuests((current) => current.filter((guest) => guest.id !== selected.id)); setGuestId(''); setUid(''); } catch (err: any) { console.error('[Cards] Assignment failed', err); showToast(err.response?.data?.message || 'This card could not be assigned. Confirm it is registered and available.', 'error'); } finally { setSaving(false); } };
  return <div className="ops-page"><EventTabs /><div className="ops-page-inner narrow"><Link to={`/events/${id}/cards`} className="back-link"><ArrowLeft size={16} /> Card inventory</Link><div className="ops-page-heading compact"><div><span className="eyebrow-label">CARD CONTROL / 02</span><h2>Assign a card to a guest</h2><p>Select the person first, then tap the NFC card on the back of the phone or use an external reader.</p></div><UserRound className="heading-mark" /></div><div className="ops-two-column"><section className="ops-panel form-panel"><span className="eyebrow-label">SELECT PERSON</span><h3>Who is receiving this card?</h3><label className="ops-label" htmlFor="assignment-guest">Eligible guests</label><select id="assignment-guest" className="ops-input" value={guestId} onChange={(e) => setGuestId(e.target.value)} disabled={saving}><option value="">Choose a confirmed, paid guest</option>{guests.map((guest) => <option key={guest.id} value={guest.id}>{guest.fullName} · {guest.category.name}</option>)}</select>{selected && <div className="selected-person"><span className="person-avatar">{selected.fullName.charAt(0)}</span><div><strong>{selected.fullName}</strong><span>{selected.category.name} · {selected.attendanceType}</span></div></div>}<button type="button" className="ops-button primary full" disabled={saving || !selected || !uid.trim()} onClick={assign}>{saving ? 'Assigning…' : 'Assign captured card'}</button></section><div><NfcCapture onUid={setUid} disabled={saving} label="Capture card for this guest" />{uid && <div className="capture-confirm"><CheckCircle2 size={17} /><span>UID captured: <b className="mono">{uid}</b></span></div>}</div></div></div></div>;
}
