import { Link, useParams } from 'react-router-dom';
import { ArrowRight, CreditCard, Plus, UserRound } from 'lucide-react';
import { useEffect, useState } from 'react';
import { cardsApi } from '../api';
import type { NfcCard } from '../types';
import EventTabs from '../components/EventTabs';
import Spinner from '../components/Spinner';
import { useUiStore } from '../store/uiStore';

export default function CardsPage() {
  const { id } = useParams<{ id: string }>(); const [cards, setCards] = useState<NfcCard[]>([]); const [loading, setLoading] = useState(true); const showToast = useUiStore((s) => s.showToast);
  useEffect(() => { cardsApi.list().then((r) => setCards(r.data)).catch((err: any) => { console.error('[Cards] Inventory load failed', err); showToast(err.response?.data?.message || 'Card inventory could not be loaded. Refresh and try again.', 'error'); }).finally(() => setLoading(false)); }, [showToast]);
  const count = (status: string) => cards.filter((card) => card.status === status).length;
  return <div className="ops-page"><EventTabs /><div className="ops-page-inner"><div className="ops-page-heading"><div><span className="eyebrow-label">EVENT ACCESS / CARD CONTROL</span><h2>NFC card inventory</h2><p>See the organization’s cards and choose a focused workflow for registration or assignment.</p></div><div className="ops-heading-actions"><Link to={`/events/${id}/cards/register`} className="ops-button primary"><Plus size={17} /> Register card</Link><Link to={`/events/${id}/cards/assign`} className="ops-button secondary"><UserRound size={17} /> Assign card</Link></div></div><div className="ops-stat-grid"><div className="ops-stat"><span>All cards</span><strong>{cards.length}</strong><small>Organization inventory</small></div><div className="ops-stat"><span>Available</span><strong>{count('AVAILABLE')}</strong><small>Ready to assign</small></div><div className="ops-stat"><span>Assigned</span><strong>{count('ASSIGNED')}</strong><small>Linked to guests</small></div><div className="ops-stat"><span>Attention</span><strong>{count('LOST') + count('DAMAGED')}</strong><small>Lost or damaged</small></div></div><section className="ops-panel"><div className="ops-panel-heading"><div><span className="eyebrow-label">LIVE INVENTORY</span><h3>Registered cards</h3></div><CreditCard size={22} /></div>{loading ? <Spinner text="Loading card inventory…" size="md" /> : cards.length === 0 ? <div className="ops-empty"><CreditCard size={28} /><strong>No cards registered</strong><span>Register the first card using phone NFC or an external reader.</span><Link to={`/events/${id}/cards/register`} className="ops-button primary">Register first card <ArrowRight size={16} /></Link></div> : <div className="ops-table-wrap"><table className="ops-table"><thead><tr><th>UID</th><th>Status</th><th>Assigned guest</th><th>Registered</th></tr></thead><tbody>{cards.map((card) => <tr key={card.uid}><td className="mono">{card.uid}</td><td><span className={`ops-pill ${card.status.toLowerCase()}`}>{card.status}</span></td><td>{card.assignedGuestName || <span className="table-muted">Unassigned</span>}</td><td>{new Date(card.registeredAt).toLocaleDateString()}</td></tr>)}</tbody></table></div>}</section></div></div>;
}
