import { Link, useParams } from 'react-router-dom';
import { ArrowRight, CreditCard, Plus, UserRound, Trash2, ShieldAlert } from 'lucide-react';
import { useEffect, useState } from 'react';
import { cardsApi } from '../api';
import type { NfcCard } from '../types';
import EventTabs from '../components/EventTabs';
import Spinner from '../components/Spinner';
import { useUiStore } from '../store/uiStore';

export default function CardsPage() {
  const { id } = useParams<{ id: string }>();
  const [cards, setCards] = useState<NfcCard[]>([]);
  const [loading, setLoading] = useState(true);
  const showToast = useUiStore((s) => s.showToast);
  useEffect(() => { if (!id) return; cardsApi.list(id).then((r) => setCards(r.data)).catch((err: any) => showToast(err.response?.data?.message || 'Card inventory could not be loaded.', 'error')).finally(() => setLoading(false)); }, [id, showToast]);
  const count = (status: string) => cards.filter((card) => card.status === status).length;
  const changeStatus = async (uid: string, status: string) => { try { const response = await cardsApi.updateStatus(uid, status); setCards((current) => current.map((card) => card.uid === uid ? response.data : card)); showToast(status === 'LOST' ? 'Card marked lost and deactivated.' : 'Card status updated.', 'success'); } catch (err: any) { showToast(err.response?.data?.message || 'Card status could not be updated.', 'error'); } };
  const removeCard = async (uid: string) => { if (!window.confirm(`Delete card ${uid}? This permanently removes its database record.`)) return; try { await cardsApi.delete(uid); setCards((current) => current.filter((card) => card.uid !== uid)); showToast('Card deleted permanently.', 'success'); } catch (err: any) { showToast(err.response?.data?.message || 'Card could not be deleted.', 'error'); } };
  return <div className="ops-page"><EventTabs /><div className="ops-page-inner"><div className="ops-page-heading"><div><span className="eyebrow-label">EVENT ACCESS / CARD CONTROL</span><h2>NFC card inventory</h2><p>Cards shown here belong only to this event and organization. Lost cards are deactivated and cannot pass the gate.</p></div><div className="ops-heading-actions"><Link to={`/events/${id}/cards/register`} className="ops-button primary"><Plus size={17} /> Register card</Link><Link to={`/events/${id}/cards/assign`} className="ops-button secondary"><UserRound size={17} /> Assign card</Link></div></div><div className="ops-stat-grid"><div className="ops-stat"><span>Event cards</span><strong>{cards.length}</strong><small>This event only</small></div><div className="ops-stat"><span>Available</span><strong>{count('AVAILABLE')}</strong><small>Ready to assign</small></div><div className="ops-stat"><span>Assigned</span><strong>{count('ASSIGNED')}</strong><small>Linked to guests</small></div><div className="ops-stat"><span>Attention</span><strong>{count('LOST') + count('DAMAGED') + count('CHECKED_IN')}</strong><small>Deactivated or used</small></div></div><section className="ops-panel"><div className="ops-panel-heading"><div><span className="eyebrow-label">LIVE INVENTORY</span><h3>Registered cards</h3></div><CreditCard size={22} /></div>{loading ? <Spinner text="Loading card inventory…" size="md" /> : cards.length === 0 ? <div className="ops-empty"><CreditCard size={28} /><strong>No cards registered for this event</strong><span>Register the first card using phone NFC or an external reader.</span><Link to={`/events/${id}/cards/register`} className="ops-button primary">Register first card <ArrowRight size={16} /></Link></div> : <div className="ops-table-wrap"><table className="ops-table"><thead><tr><th>UID</th><th>Status</th><th>Assigned guest</th><th>Registered</th><th>Admin actions</th></tr></thead><tbody>{cards.map((card) => <tr key={card.uid}><td className="mono">{card.uid}</td><td><span className={`ops-pill ${card.status.toLowerCase()}`}>{card.status === 'CHECKED_IN' ? 'CHECKED IN' : card.status}</span></td><td>{card.assignedGuestName || <span className="table-muted">Unassigned</span>}</td><td>{new Date(card.registeredAt).toLocaleDateString()}</td><td><div className="flex gap-1">{card.status !== 'LOST' && card.status !== 'CHECKED_IN' && <button className="ops-button secondary" onClick={() => changeStatus(card.uid, 'LOST')} title="Mark lost"><ShieldAlert size={14} /> Lost</button>}<button className="ops-button secondary" onClick={() => removeCard(card.uid)} title="Delete card"><Trash2 size={14} /> Delete</button></div></td></tr>)}</tbody></table></div>}</section></div></div>;
}
