import { Link, useParams } from 'react-router-dom';
import { ArrowLeft, CheckCircle2, UserRound } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { cardsApi, guestsApi } from '../api';
import type { Guest } from '../types';
import EventTabs from '../components/EventTabs';
import NfcCapture from '../components/NfcCapture';
import { useUiStore } from '../store/uiStore';

export default function CardAssignmentPage() {
  const { id } = useParams<{ id: string }>(); const [guests, setGuests] = useState<Guest[]>([]); const [guestId, setGuestId] = useState(''); const [uid, setUid] = useState(''); const [saving, setSaving] = useState(false); const showToast = useUiStore((s) => s.showToast);
  const orderedGuests = useMemo(() => [...guests].sort((a, b) => a.category.priorityLevel - b.category.priorityLevel || a.fullName.localeCompare(b.fullName)), [guests]);
  useEffect(() => { if (!id) return; guestsApi.assignable(id).then((r) => { const sorted = [...r.data].sort((a, b) => a.category.priorityLevel - b.category.priorityLevel || a.fullName.localeCompare(b.fullName)); setGuests(sorted); setGuestId(sorted[0]?.id || ''); }).catch((err: any) => { console.error('[Cards] Assignable guests load failed', err); showToast(err.response?.data?.message || 'Eligible guests could not be loaded. Refresh and try again.', 'error'); }); }, [id, showToast]);
  const selected = orderedGuests.find((guest) => guest.id === guestId);
  const assign = async (guest: Guest | undefined, capturedUid: string) => { if (!guest || !capturedUid.trim()) return; setSaving(true); setUid(capturedUid.trim()); try { await cardsApi.assign(guest.id, capturedUid.trim()); showToast(`Card assigned to ${guest.fullName}.`, 'success'); const remaining = orderedGuests.filter((candidate) => candidate.id !== guest.id); setGuests(remaining); setGuestId(remaining[0]?.id || ''); setUid(''); } catch (err: any) { console.error('[Cards] Assignment failed', err); showToast(err.response?.data?.message || 'This card could not be assigned. Confirm it is registered and available.', 'error'); } finally { setSaving(false); } };
  const handleUid = (capturedUid: string) => { setUid(capturedUid); void assign(selected, capturedUid); };
  return <div className="ops-page"><EventTabs /><div className="ops-page-inner narrow"><Link to={`/events/${id}/cards`} className="back-link"><ArrowLeft size={16} /> Card inventory</Link><div className="ops-page-heading compact"><div><span className="eyebrow-label">CARD CONTROL / 02</span><h2>Assign a card to a guest</h2><p>Select a guest, then tap a card. Captured cards are assigned automatically; the next guest becomes ready.</p></div><UserRound className="heading-mark" /></div><div className="ops-two-column"><section className="ops-panel form-panel"><span className="eyebrow-label">SELECT PERSON</span><h3>Who is receiving this card?</h3><label className="ops-label" htmlFor="assignment-guest">Eligible guests</label><select id="assignment-guest" className="ops-input" value={guestId} onChange={(e) => setGuestId(e.target.value)} disabled={saving}><option value="">Choose a confirmed, paid guest</option>{orderedGuests.map((guest) => <option key={guest.id} value={guest.id}>{guest.fullName} ({guest.category.name})</option>)}</select>{selected && <div className="selected-person"><span className="person-avatar">{selected.fullName.charAt(0)}</span><div><strong>{selected.fullName}</strong><span>{selected.category.name} · {selected.attendanceType === 'PLUS_ONE' ? 'Plus one' : 'Single'}</span></div></div>}{saving && <div className="capture-confirm"><CheckCircle2 size={17} /><span>Assigning captured card…</span></div>}</section><div><NfcCapture onUid={handleUid} disabled={saving || !selected} label="Capture card for this guest" />{uid && !saving && <div className="capture-confirm"><CheckCircle2 size={17} /><span>UID captured: <b className="mono">{uid}</b></span></div>}</div></div></div></div>;
}
