import { ArrowRight, CalendarDays, LoaderCircle, Plus, Sparkles } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { eventsApi } from '../api';
import { useAuthStore } from '../store/authStore';
import { useUiStore } from '../store/uiStore';
import type { Event } from '../types';
import { formatDate, statusColors } from '../lib/utils';
import SEO from '../components/SEO';
import Spinner from '../components/Spinner';

export default function DashboardPage() {
  const [events, setEvents] = useState<Event[]>([]); const [loading, setLoading] = useState(true); const [openingEventId, setOpeningEventId] = useState<string | null>(null); const user = useAuthStore((s) => s.user); const showToast = useUiStore((s) => s.showToast); const canCreate = user?.role === 'ADMIN';
  useEffect(() => { eventsApi.list().then((r) => setEvents(r.data)).catch((err: any) => { console.error('[Dashboard] Events load failed', err); showToast(err.response?.data?.message || 'Events could not be loaded. Refresh and try again.', 'error'); }).finally(() => setLoading(false)); }, [showToast]);
  const openEvent = (eventId: string) => { if (openingEventId) return; setOpeningEventId(eventId); };
  return <div className="ops-page"><SEO title="Events workspace | Occassia" description="Manage events, guest access, NFC cards, and live attendance from the Occassia workspace." noIndex /><div className="ops-page-inner"><section className="dashboard-welcome"><div><span className="eyebrow-label"><Sparkles size={12} /> OCCASSIA WORKSPACE</span><h2>Your events, in one clear view.</h2><p>Choose an event to manage guests, prepare NFC access, or watch the entrance live.</p></div>{canCreate && <Link to="/events/new" className="ops-button primary"><Plus size={17} /> Create event</Link>}</section><div className="dashboard-overview"><div><span>Active workspace</span><strong>{events.filter((event) => event.status === 'ACTIVE').length}</strong><small>events in progress</small></div><div><span>Upcoming</span><strong>{events.filter((event) => event.status === 'DRAFT').length}</strong><small>events being prepared</small></div><div><span>Role</span><strong className="role-value">{user?.role?.replace('_', ' ') || 'Operator'}</strong><small>current access level</small></div></div><div className="ops-section-heading"><div><span className="eyebrow-label">EVENT SPACES</span><h3>Recent events</h3></div>{events.length > 0 && <span className="section-count">{events.length} total</span>}</div>{loading ? <div className="ops-panel"><Spinner text="Loading events…" useLogo size="lg" /></div> : events.length === 0 ? <div className="ops-panel ops-empty"><CalendarDays size={30} /><strong>No events yet</strong><span>Create an event to start building your guest experience.</span>{canCreate && <Link to="/events/new" className="ops-button primary">Create first event <ArrowRight size={16} /></Link>}</div> : <div className="event-card-grid">{events.map((event) => <Link className={`event-card-new ${openingEventId === event.id ? 'is-opening' : ''}`} to={`/events/${event.id}`} key={event.id} onClick={(e) => { if (openingEventId) e.preventDefault(); else openEvent(event.id); }} aria-busy={openingEventId === event.id}><div className="event-card-top"><span className="event-type">{event.type}</span><span className={`event-status ${statusColors[event.status]}`}>{event.status}</span></div><h3>{event.name}</h3><p>{formatDate(event.startDate || event.eventDate)}</p>{event.venue && <span className="event-venue">{event.venue}</span>}<span className="event-card-arrow">{openingEventId === event.id ? <LoaderCircle size={17} className="event-opening-spinner" aria-label="Opening event" /> : <ArrowRight size={16} />}</span></Link>)}</div>}</div></div>;
}
